package com.binaryigor.expressor.generator;

import com.binaryigor.expressor.spec.AppSpec;

public interface AppGenerator {

    String GENERATED_BY_MARKER = "Generated by Expressor";

    void generate(AppSpec appSpec);
}
